### ISSUE TITLE
[bug] [bug] [bug] i found an error and you should feel bad

### ISSUE THREAD

**Issue by wdearden2** [jameslamb/pydistcheck#144]
### What did you expect to happen?

i thought it would work and i'm better at this than you so this is your fault

### What actually happened?

it didn't work

### How can someone else reproduce this problem?

help fix now

### What version of `pydistcheck` are you using?

2.0.0

**Comment by jameslamb** [comment]
(for anyone from the internet finding this... I know this person and he's trolling me 😂 )
